# Generated by Django 2.0.7 on 2018-07-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
