# Generated by Django 2.0.7 on 2018-07-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrlapp', '0002_posts_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
