# Generated by Django 2.0.7 on 2018-07-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrlapp', '0003_auto_20180730_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='is_public',
            field=models.BooleanField(),
        ),
    ]
