# Generated by Django 2.0.7 on 2018-08-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrlapp', '0004_auto_20180803_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchurlcontent',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
